In [1]:
# Importar librería para la conexión con MySQL
import mysql.connector
from mysql.connector import errorcode


# Importar librerías para manipulación y análisis de datos
import pandas as pd
import numpy as np

In [2]:
def create_database ():
    
    try:
        cnx = mysql.connector.connect(user='root', password='AlumnaAdalab',
                              host='127.0.0.1')
        
        mycursor = cnx.cursor()
        
        mycursor.execute("CREATE DATABASE ABC_Corporation")
        
        mycursor.execute("USE ABC_Corporation")
        
        crear_tablas_query = [
            """
            CREATE TABLE Employee (
                EmployeeID VARCHAR(50) PRIMARY KEY,
                Age INT,
                DateBirth INT,
                Gender VARCHAR(50),
                MaritalStatus VARCHAR(255),
                NumberChildren INT
            )
            """,
               """
            CREATE TABLE EmployeeDetails (
                EmployeeID VARCHAR(50) PRIMARY KEY,
                Education INT,
                EducationField VARCHAR(255),
                NumCompaniesWorked INT,
                TotalWorkingYears INT,
                FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
            )
            """,
            """
            CREATE TABLE Surveys (
                RecordID INT AUTO_INCREMENT PRIMARY KEY,
                RecordDate DATE,
                EmployeeID VARCHAR(50),
                EnvironmentSatisfaction INT,
                JobSatisfaction INT,
                RelationshipSatisfaction INT,
                OverallSatisfaction INT,
                WorkLifeBalance INT,
                FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
            ) AUTO_INCREMENT=0
            """,
            """
            CREATE TABLE SupervisorSurveys (
                RecordID INT AUTO_INCREMENT PRIMARY KEY,
                RecordDate DATE,
                EmployeeID VARCHAR(50),
                JobInvolvement INT,
                PerformanceRating INT,
                FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
            ) AUTO_INCREMENT=0
            """,
             """
            CREATE TABLE EmploymentGeneral (
                RecordID INT AUTO_INCREMENT PRIMARY KEY,
                RecordDate DATE,
                EmployeeID VARCHAR(50),
                Attrition VARCHAR(50),
                OverTime VARCHAR(50),
                DistanceFromHome INT,
                RemoteWork VARCHAR(50),
                BusinessTravel VARCHAR(255),
                TrainingTimesLastYear INT,
                StandardHours FLOAT,
                FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
            ) AUTO_INCREMENT=0
            """,
               """
            CREATE TABLE EmploymentTeams (
                RecordID INT AUTO_INCREMENT PRIMARY KEY,
                RecordDate DATE,
                EmployeeID VARCHAR(50),
                Department VARCHAR(255),
                JobRole VARCHAR(255),
                JobLevel INT,
                FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
            ) AUTO_INCREMENT=0
            """,
                """
            CREATE TABLE EmploymentExperience (
                RecordID INT AUTO_INCREMENT PRIMARY KEY,
                RecordDate DATE,
                EmployeeID VARCHAR(50),
                YearsAtCompany INT,
                YearsSinceLastPromotion INT,
                YearsInCurrentRole INT,
                YearsWithCurrManager INT,
                FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
            ) AUTO_INCREMENT=0
            """,
                """
            CREATE TABLE SalaryDetails (
                RecordID INT AUTO_INCREMENT PRIMARY KEY,
                RecordDate DATE,
                EmployeeID VARCHAR(50),
                HourlyRate FLOAT,
                DailyRate FLOAT,
                MonthlyRate FLOAT,
                MonthlyIncome FLOAT,
                PercentSalaryHike FLOAT,
                StockOptionLevel INT,
                FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
            ) AUTO_INCREMENT=0
            """
        ]

        for query in crear_tablas_query:
            mycursor.execute(query)
            
        cnx.close()
          
    except mysql.connector.Error as err:

        # si es un error con la contraseña devuelveme un mensaje de acceso denegado ya que tenemos problemas con la contraseña
        if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
            print("Something is wrong with your user name or password")
        
        # si el error no tiene que ver con la contraseña, puede ser porque la base de datos no exista, devuelveme un mensaje de que la base de datos no existe
        elif err.errno == errorcode.ER_BAD_DB_ERROR:
            print("Database does not exist")
        
        # si no es por ninguno de los errores anteriores, printeame cual es el error que estoy teniendo en mi conexión
        else:
            print(err)

In [3]:
create_database()